### ISSUE TITLE
[Question]: Hook up an existing EFS "file system"?

### ISSUE THREAD

**Issue by farahfa** [cloudfoundry-incubator/efs-volume-release#4]
Hello,

From my understanding, this project creates an EFS file system and then gives you the ability to mount it to cf containers. I already have an EFS file system, and I want to be able to bind it to an app (cf container), how can I do that?

Fadi

**Comment by julian-hj** [comment]
We don't support that use case today.  We have seen some customers mount the EFS volume to a bare EC2 vm, and then re-share the mount from that VM using the nfs kernel server (which creates an nfs v3 share)  From there you can mount the share using nfs-volume-release.  

But that's kind of a hack.  I am guessing you have a lot of data, so you don't want to copy it onto an efs-volume-release provisioned share?

**Comment by farahfa** [comment]
Yes, unfortunately there are a lot of data that can't just be transferred easily. Hmm, I knew about the "re-share" option, but I'm worried about the performance issues associated with that; I guess we could  test out that work-around and see how that works.

**Comment by julian-hj** [comment]
Yes, you are right to worry about performance if you have very large data. The nfs driver uses a fuse mount and also nfs3.  Both of those are bad for performance.  Do let us know if you try it out, as we don't have a clear sense for exactly how much performance will suffer going through the nfs3/fuse mechanism.

As a side question, if we were to implement an option to mount existing EFS volumes, we would need to decide who should create the mount point in that case.  For your use case, would you prefer to have the mount points already created and let the application developer specify them when the service instance is created?  Or would you want the service broker to create the mount point into the appropriate AZs?  Or would it be better to just specify the available EFS volumes as plans in a service catalog, so that the application developer can only choose from one of a list of available EFS volumes?

**Comment by julian-hj** [comment]
This use case is now supported from nfs-volume-release, using nfs-experimental mounts with "version": "4.1"

Please see the instructions here:
https://github.com/cloudfoundry/nfs-volume-release#nfs-v4-experimental

I am going to close this issue, but please feel free to open a new one in nfs-volume-release if that solution doesn't work for you or you have questions.  Thanks!
